# Docker Compose configuration for running Bats tests
# This creates an isolated environment with all dependencies needed to test the plugin

services:
  # Test runner service - runs our Bats tests in a controlled environment
  tests:
    # Use official Bats image which includes Bats testing framework pre-installed
    image: bats/bats:latest
    
    # Mount our project directory into the container
    volumes:
      # Mount the entire project directory (need write access for test helpers)
      - .:/code
    
    # Set the working directory inside the container
    working_dir: /code
    
    # Run the test script
    command: ./run-tests.sh
    
    # Set environment variables needed for testing
    environment:
      # Disable terminal colors for cleaner test output in CI
      - NO_COLOR=1
      # Set a fake Buildkite job ID for testing
      - BUILDKITE_JOB_ID=test-job-12345