name: ChatGPT Log Plugin
description: Automatically analyzes failed Buildkite job logs using OpenAI's ChatGPT and provides intelligent suggestions for fixing issues through build annotations.
author: AthreyaRay
requirements:
- curl
- jq
- buildkite-agent with --enable-job-log-tmpfile flag
configuration:
  properties:
    max_tokens:
      type: number
      default: 1500
      description: "Maximum tokens for ChatGPT response (controls cost)"
    model:
      type: string
      default: "gpt-4o-mini"
      description: "OpenAI model to use (gpt-4o-mini is cheaper than gpt-4o)"
    max_log_lines:
      type: number
      default: 600
      description: "Maximum number of log lines to analyze"
    timeout:
      type: number
      default: 30
      description: "API request timeout in seconds"
  additionalProperties: false
